package life.majiang.community.mapper;

import java.util.List;
import life.majiang.community.model.AD;
import life.majiang.community.model.ADExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ADMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AD
     *
     * @mbg.generated Thu May 13 23:45:31 CST 2021
     */
    long countByExample(ADExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AD
     *
     * @mbg.generated Thu May 13 23:45:31 CST 2021
     */
    int deleteByExample(ADExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AD
     *
     * @mbg.generated Thu May 13 23:45:31 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AD
     *
     * @mbg.generated Thu May 13 23:45:31 CST 2021
     */
    int insert(AD record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AD
     *
     * @mbg.generated Thu May 13 23:45:31 CST 2021
     */
    int insertSelective(AD record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AD
     *
     * @mbg.generated Thu May 13 23:45:31 CST 2021
     */
    List<AD> selectByExampleWithRowbounds(ADExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AD
     *
     * @mbg.generated Thu May 13 23:45:31 CST 2021
     */
    List<AD> selectByExample(ADExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AD
     *
     * @mbg.generated Thu May 13 23:45:31 CST 2021
     */
    AD selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AD
     *
     * @mbg.generated Thu May 13 23:45:31 CST 2021
     */
    int updateByExampleSelective(@Param("record") AD record, @Param("example") ADExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AD
     *
     * @mbg.generated Thu May 13 23:45:31 CST 2021
     */
    int updateByExample(@Param("record") AD record, @Param("example") ADExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AD
     *
     * @mbg.generated Thu May 13 23:45:31 CST 2021
     */
    int updateByPrimaryKeySelective(AD record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AD
     *
     * @mbg.generated Thu May 13 23:45:31 CST 2021
     */
    int updateByPrimaryKey(AD record);
}